repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    exclude: lib
  - id: end-of-file-fixer
    exclude: lib
  - id: debug-statements
    exclude: lib
  - id: check-merge-conflict

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.2
  hooks:
  - id: seed-isort-config
    args: [--application-directories=starry, --exclude=lib]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    args: []
    exclude: lib

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3.7
    exclude: lib

- repo: https://github.com/dfm/black_nbconvert
  rev: stable
  hooks:
  - id: black_nbconvert
    exclude: lib
