# Adapted from http://dfm.io/posts/travis-latex/
sudo: required

dist: trusty

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5

env:
     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

install:
    - source .ci/travis.sh

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - py.test -v -s

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-paper.sh; fi
