# Adapted from http://dfm.io/posts/travis-latex/
sudo: required

dist: trusty

language: c

addons:
    apt:
        packages:
            - gcc-4.8
            - g++-4.8

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

install:
    - source .ci/travis.sh

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - py.test -v -s

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then source .ci/build-docs.sh; fi
    - source .ci/build-paper.sh
