# Adapted from dfm/george

language: python

matrix:
  include:
    - python: 3.4

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy matplotlib nose sympy mpmath
  - ln -sf $(which gcc) x86_64-conda_cos6-linux-gnu-gcc
  - python setup.py develop

script:
  - nosetests --with-coverage --cover-package=starry -v -w tests
