# Adapted from http://dfm.io/posts/travis-latex/
sudo: false

language: generic

matrix:
    include:
        - os: linux
              env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

install:
    - source .ci/travis.sh

script: |
    py.test -v --cov starry
    source .ci/build-paper.sh
      