# Adapted from http://dfm.io/posts/travis-latex/
sudo: required

dist: trusty

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

install:
    - source .ci/travis.sh
    - export CC=gcc-4.8
    - export CXX=g++-4.8
    - travis_wait 30 python setup.py develop

cache:
    directories:
        - $HOME/miniconda
        - $HOME/.cache/Tectonic

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - py.test -v -s

after_success:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-paper.sh; fi
    # DEBUG:                 "master"
    - if [ "$TRAVIS_BRANCH" = "dev" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
