jobs:
- job: Default
  timeoutInMinutes: 60
  pool:
    vmImage: Ubuntu-16.04
  steps:
  - script: |
      nproc
      lscpu
    displayName: 'Machine info'
  - script: |
      sudo chown -R $USER $CONDA
      . $CONDA/etc/profile.d/conda.sh
      conda create --yes --quiet --name starry python=3.7.3 pip
    displayName: 'Setup conda'
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate starry
      conda install -y -q numpy scipy mkl openblas theano
      theano-cache purge
      pip install -U pip
      pip install -U setuptools
      pip install -U parameterized nose pytest sphinx nbsphinx
      git clone https://github.com/rodluger/starry_beta
      pip install -U -r requirements.txt
      pip install -U -r optional-requirements.txt
      pushd starry_beta
      python setup.py develop
      popd
    displayName: 'Install dependencies'
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate starry
      python setup.py develop
    displayName: 'Install starry'
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate starry
      py.test -v -s tests/lazy
      py.test -v -s tests/greedy
    displayName: 'Run tests'
  - script: |
      . $CONDA/etc/profile.d/conda.sh
      conda activate starry
      # Build the docs
      make -C docs html
      cd docs/_build
      # Clone the `gh-pages` branch
      mkdir gh-pages
      cd gh-pages
      git clone -b gh-pages --single-branch https://github.com/rodluger/starry.git .
      # Reset git tracking & update the current version's docs
      rm -rf .git
      STARRY_VERSION=$(python -c "import starry; print('v' + starry.__version__)")
      rm -rf $STARRY_VERSION/*
      mkdir -p $STARRY_VERSION
      mv ../html/* $STARRY_VERSION/
      # Commit & force push back
      git init
      touch .nojekyll
      git add -f .nojekyll
      git add -f *
      git -c user.name='rodluger' -c user.email='rodluger@gmail.com' commit -m "rebuild gh-pages for ${STARRY_VERSION}"
      # DEBUG
      echo $(GITHUB_API_KEY) | head -c 3
      echo $(GITHUB_USER)
      # DEBUG
      echo $(GITHUB_API_KEY) | tail -c 3
      echo $(GITHUB_USER)
      # DEBUG
      git push -f https://rodluger:$(GITHUB_API_KEY)@github.com/rodluger/starry HEAD:gh-pages #>/dev/null 2>&1 #-q
      cd ../../
    displayName: 'Build docs'