jobs:
- job: Default
  timeoutInMinutes: 60
  pool:
    vmImage: Ubuntu-16.04
  steps:

  - bash: .ci/setup.sh
    displayName: 'Setup'

  - bash: .ci/run_tests.sh
    displayName: 'Run tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results'
