trigger:
  - dev
  - master

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    vmImage: Ubuntu-16.04
  steps:

  - bash: .ci/setup.sh
    displayName: 'Setup'

  - bash: .ci/run_notebooks.sh
    displayName: 'Run notebooks'

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/docs/notebooks
      artifact: Notebooks
