name: tests

on:
  push:
    branches: [master,restructure]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pymc-version: ["pymc3==3.9.3", "pymc3==3.10", "pymc3==3.11", "https://github.com/pymc-devs/pymc3/archive/master.zip"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.pymc-version }}-

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry
          environment-file: environment.yml

      - name: Set up environment
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip uninstall -y theano  # so that we know which version we're getting
          python -m pip install ${{ matrix.pymc-version }}
          python -m pip install -e ".[tests]"
          python -c 'import theano; print(theano.__version__)'
          python -m pip install -U git+https://github.com/rodluger/coverage-badge

      - name: Run tests (greedy)
        shell: bash -l {0}
        run: python -m pytest -v tests/greedy --junitxml=junit/test-results-greedy.xml --cov=starry --cov-append --cov-report html:coverage --cov-config=.github/workflows/.coveragerc tests/greedy

      - name: Run tests (lazy)
        shell: bash -l {0}
        run: python -m pytest -v tests/lazy --junitxml=junit/test-results-lazy.xml --cov=starry --cov-append --cov-report html:coverage --cov-config=.github/workflows/.coveragerc tests/lazy
        if: ${{ always() }}

      - name: Run extension tests (greedy)
        shell: bash -l {0}
        run: python -m pytest -v starry/extensions/tests/greedy --junitxml=junit/test-results-extensions-greedy.xml --cov=starry --cov-append --cov-report html:coverage-extensions --cov-config=.github/workflows/.coveragerc_extensions starry/extensions/tests/greedy
        if: ${{ always() }}

      - name: Run extension tests (lazy)
        shell: bash -l {0}
        run: python -m pytest -v starry/extensions/tests/lazy --junitxml=junit/test-results-extensions-lazy.xml --cov=starry --cov-append --cov-report html:coverage-extensions --cov-config=.github/workflows/.coveragerc_extensions starry/extensions/tests/lazy
        if: ${{ always() }}

      - name: Generate coverage badges
        shell: bash -l {0}
        run: |
          coverage-badge -o coverage/coverage.svg
          coverage-badge -n extensions.svg -o coverage-extensions/coverage.svg
        if: always() && matrix.pymc-version == "pymc3==3.9.3"

      - name: Get unique id
        id: unique-id
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: |
          export JOB_ID=`echo $STRATEGY_CONTEXT | md5sum`
          echo "::set-output name=id::$JOB_ID"
        if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ steps.unique-id.outputs.id }}
          path: junit/test-*.xml
        if: always()

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit/test-*.xml

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ steps.unique-id.outputs.id }}
          path: coverage
        if: always() && matrix.pymc-version == "pymc3==3.9.3"

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-extensions-${{ steps.unique-id.outputs.id }}
          path: coverage-extensions
        if: always() && matrix.pymc-version == "pymc3==3.9.3"
